# Site wide configuration

title: "LittleSakana Development"
description: "开发学习过程笔记及开发经验积累，以供参考"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_CN
url: ""
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  input: GFM
  syntax_highlighter: rouge
  toc_levels: 1..6
#markdown: redcarpet
#redcarpet:
    #extensions: [ "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]
#kramdown:
  #input: GFM
  #toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: "LittleSakana"
  web: "http://www.overFlowStack.com/about"
  twitter: "Littlesakana"
  bio: "既然目标是地平线，留给世界的只能是背影"
  avatar: "profile.jpeg" # 160x160 px image for author byline
  #google:
    #plus: "+MichaelRoseDesign"
    #ad-client: "ca-pub-7328585512091257"
    #ad-slot: 3049671934
  #comments :
  #provider : duoshuo
  #duoshuo :
  #  short_name : overflowstack


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
